/* ============================================================
   Base de dados dos 12 signos
   Formato da data: "MM-DD"
   ============================================================ */

const SIGNOS = [
    {
        nome: 'Áries',
        slug: 'aries',
        simbolo: '♈',
        dataInicio: '03-21',
        dataFim: '04-19',
        elemento: 'Fogo',
        modalidade: 'Cardinal',
        regente: 'Marte',
        periodo: '21 de março a 19 de abril',
        descricao: 'Áries é o pioneiro do zodíaco: age por impulso, ama desafios e não tem paciência para rodeios. Sua energia contagiante abre caminhos, mas a impulsividade exige atenção.',
        caracteristicas: ['Corajoso', 'Determinado', 'Entusiasta', 'Impulsivo', 'Competitivo'],
        afinidades: ['Leão', 'Sagitário', 'Gêmeos', 'Aquário'],
        sorte: 'Cor: vermelho • Pedra: diamante • Dia: terça-feira'
    },
    {
        nome: 'Touro',
        slug: 'touro',
        simbolo: '♉',
        dataInicio: '04-20',
        dataFim: '05-20',
        elemento: 'Terra',
        modalidade: 'Fixo',
        regente: 'Vênus',
        periodo: '20 de abril a 20 de maio',
        descricao: 'Touro valoriza segurança, conforto e estabilidade. Paciente e persistente, constrói suas conquistas passo a passo e dificilmente abre mão daquilo que considera seu.',
        caracteristicas: ['Paciente', 'Confiável', 'Persistente', 'Teimoso', 'Sensual'],
        afinidades: ['Virgem', 'Capricórnio', 'Câncer', 'Peixes'],
        sorte: 'Cor: verde • Pedra: esmeralda • Dia: sexta-feira'
    },
    {
        nome: 'Gêmeos',
        slug: 'gemeos',
        simbolo: '♊',
        dataInicio: '05-21',
        dataFim: '06-20',
        elemento: 'Ar',
        modalidade: 'Mutável',
        regente: 'Mercúrio',
        periodo: '21 de maio a 20 de junho',
        descricao: 'Curioso e comunicativo, Gêmeos vive de ideias, conversas e novidades. Adapta-se rapidamente a qualquer ambiente, mas pode se dispersar com facilidade.',
        caracteristicas: ['Comunicativo', 'Versátil', 'Curioso', 'Ágil', 'Inconstante'],
        afinidades: ['Libra', 'Aquário', 'Áries', 'Leão'],
        sorte: 'Cor: amarelo • Pedra: ágata • Dia: quarta-feira'
    },
    {
        nome: 'Câncer',
        slug: 'cancer',
        simbolo: '♋',
        dataInicio: '06-21',
        dataFim: '07-22',
        elemento: 'Água',
        modalidade: 'Cardinal',
        regente: 'Lua',
        periodo: '21 de junho a 22 de julho',
        descricao: 'Sensível e protetor, Câncer tem forte ligação com a família e o lar. Intuitivo, capta o clima emocional do ambiente antes mesmo de qualquer palavra ser dita.',
        caracteristicas: ['Sensível', 'Protetor', 'Intuitivo', 'Leal', 'Emotivo'],
        afinidades: ['Escorpião', 'Peixes', 'Touro', 'Virgem'],
        sorte: 'Cor: prata • Pedra: pérola • Dia: segunda-feira'
    },
    {
        nome: 'Leão',
        slug: 'leao',
        simbolo: '♌',
        dataInicio: '07-23',
        dataFim: '08-22',
        elemento: 'Fogo',
        modalidade: 'Fixo',
        regente: 'Sol',
        periodo: '23 de julho a 22 de agosto',
        descricao: 'Leão brilha por onde passa. Criativo, generoso e cheio de presença, gosta de ser reconhecido e lidera com carisma — desde que receba a devida atenção.',
        caracteristicas: ['Carismático', 'Generoso', 'Criativo', 'Confiante', 'Orgulhoso'],
        afinidades: ['Áries', 'Sagitário', 'Libra', 'Gêmeos'],
        sorte: 'Cor: dourado • Pedra: rubi • Dia: domingo'
    },
    {
        nome: 'Virgem',
        slug: 'virgem',
        simbolo: '♍',
        dataInicio: '08-23',
        dataFim: '09-22',
        elemento: 'Terra',
        modalidade: 'Mutável',
        regente: 'Mercúrio',
        periodo: '23 de agosto a 22 de setembro',
        descricao: 'Virgem observa detalhes que ninguém mais vê. Prático, organizado e analítico, busca a perfeição em tudo — e às vezes cobra demais de si mesmo.',
        caracteristicas: ['Organizado', 'Analítico', 'Prático', 'Detalhista', 'Crítico'],
        afinidades: ['Touro', 'Capricórnio', 'Câncer', 'Escorpião'],
        sorte: 'Cor: bege • Pedra: safira • Dia: quarta-feira'
    },
    {
        nome: 'Libra',
        slug: 'libra',
        simbolo: '♎',
        dataInicio: '09-23',
        dataFim: '10-22',
        elemento: 'Ar',
        modalidade: 'Cardinal',
        regente: 'Vênus',
        periodo: '23 de setembro a 22 de outubro',
        descricao: 'Libra é o signo do equilíbrio e das relações. Diplomático, estético e sociável, evita conflitos e busca harmonia — mas pode ter dificuldade em tomar decisões.',
        caracteristicas: ['Diplomático', 'Sociável', 'Elegante', 'Justo', 'Indeciso'],
        afinidades: ['Gêmeos', 'Aquário', 'Leão', 'Sagitário'],
        sorte: 'Cor: rosa • Pedra: opala • Dia: sexta-feira'
    },
    {
        nome: 'Escorpião',
        slug: 'escorpiao',
        simbolo: '♏',
        dataInicio: '10-23',
        dataFim: '11-21',
        elemento: 'Água',
        modalidade: 'Fixo',
        regente: 'Plutão',
        periodo: '23 de outubro a 21 de novembro',
        descricao: 'Intenso e magnético, Escorpião sente tudo em profundidade. Leal a quem confia, tem faro para segredos e uma força de vontade difícil de dobrar.',
        caracteristicas: ['Intenso', 'Leal', 'Estratégico', 'Magnético', 'Desconfiado'],
        afinidades: ['Câncer', 'Peixes', 'Virgem', 'Capricórnio'],
        sorte: 'Cor: vinho • Pedra: topázio • Dia: terça-feira'
    },
    {
        nome: 'Sagitário',
        slug: 'sagitario',
        simbolo: '♐',
        dataInicio: '11-22',
        dataFim: '12-21',
        elemento: 'Fogo',
        modalidade: 'Mutável',
        regente: 'Júpiter',
        periodo: '22 de novembro a 21 de dezembro',
        descricao: 'Sagitário precisa de horizonte aberto. Otimista, sincero e aventureiro, busca sentido em cada experiência e não suporta se sentir preso.',
        caracteristicas: ['Otimista', 'Aventureiro', 'Sincero', 'Expansivo', 'Impulsivo'],
        afinidades: ['Áries', 'Leão', 'Libra', 'Aquário'],
        sorte: 'Cor: azul • Pedra: turquesa • Dia: quinta-feira'
    },
    {
        nome: 'Capricórnio',
        slug: 'capricornio',
        simbolo: '♑',
        dataInicio: '12-22',
        dataFim: '01-19',
        elemento: 'Terra',
        modalidade: 'Cardinal',
        regente: 'Saturno',
        periodo: '22 de dezembro a 19 de janeiro',
        descricao: 'Capricórnio constrói pensando no longo prazo. Disciplinado, responsável e ambicioso, alcança suas metas com paciência — mas precisa aprender a relaxar.',
        caracteristicas: ['Disciplinado', 'Responsável', 'Ambicioso', 'Prático', 'Reservado'],
        afinidades: ['Touro', 'Virgem', 'Escorpião', 'Peixes'],
        sorte: 'Cor: cinza • Pedra: ônix • Dia: sábado'
    },
    {
        nome: 'Aquário',
        slug: 'aquario',
        simbolo: '♒',
        dataInicio: '01-20',
        dataFim: '02-18',
        elemento: 'Ar',
        modalidade: 'Fixo',
        regente: 'Urano',
        periodo: '20 de janeiro a 18 de fevereiro',
        descricao: 'Aquário pensa à frente do seu tempo. Original, independente e humanitário, questiona padrões e valoriza a liberdade acima de quase tudo.',
        caracteristicas: ['Original', 'Independente', 'Humanitário', 'Inventivo', 'Distante'],
        afinidades: ['Gêmeos', 'Libra', 'Áries', 'Sagitário'],
        sorte: 'Cor: turquesa • Pedra: ametista • Dia: sábado'
    },
    {
        nome: 'Peixes',
        slug: 'peixes',
        simbolo: '♓',
        dataInicio: '02-19',
        dataFim: '03-20',
        elemento: 'Água',
        modalidade: 'Mutável',
        regente: 'Netuno',
        periodo: '19 de fevereiro a 20 de março',
        descricao: 'Peixes é sensível, imaginativo e empático. Vive entre a razão e a fantasia, tem grande intuição artística e absorve facilmente as emoções ao redor.',
        caracteristicas: ['Empático', 'Imaginativo', 'Intuitivo', 'Artístico', 'Sensível'],
        afinidades: ['Câncer', 'Escorpião', 'Touro', 'Capricórnio'],
        sorte: 'Cor: lilás • Pedra: água-marinha • Dia: quinta-feira'
    }
];